### ISSUE TITLE
Get same Adafruit GPIO ribbon cable from DigiKey & save shipping

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#108]
The SAME 6" 40 connector GPIO ribbon listed in the parts spreadsheet from Adafruit:
[https://www.adafruit.com/product/1988](url)
can be purchased from DigiKey along with the other parts & save separate shipping:
[https://www.digikey.com/product-detail/en/adafruit-industries-llc/1988/1528-2235-ND/7241480](url)
Jim Phelan
Mars Rover project lead
USAi Labs (formerly Houston Robotics)

**Comment by ericjunkins** [comment]
Sure thing good find. Would you mind opening a pull request with that changed in the parts list and I'll merge it in

**Comment by lukeweston** [comment]
All Adafruit items can be ordered from Digi-Key, which is generally the most convenient and cheapest way if you're ordering from Digi-Key anyway.

**Comment by vssystemluba** [comment]
Since we order parts from both DigiKey and Adafruit for the whole rover, I'll leave this as it is for now.  You only save shipping if you are only ordering upgraded parts for the electronics-pcb-rework branch.
