### ISSUE TITLE
Decoupling capacitors on opamps

### ISSUE THREAD

**Issue by lukeweston** [nasa-jpl/open-source-rover#110]
A decoupling capacitor (say 100nF) should be provided at the Vcc pin on each of the voltage-follower opamps in the encoder system. Given the use of long wires and amateur construction with DuPont jumper wires, parasitic inductance in the 5V supply wires is likely to be significant, and the proper use of decoupling capacitors at each IC is universally good practice.

The master BOM says that 4x LM358 are used - but is this correct?
There are 4 encoder channels, so 2 LM358s should be needed. (They are a dual opamp.)
In fact, a single quad opamp could be used (eg. LM324) meaning one less part.

15kΩ : 10kΩ would provide the most correct voltage division of 5V to 2V, assuming zero output impedance in the encoder, and remains a common E12 value.

Wouldn't choosing an encoder with TTL quadrature output and connecting this to the motor drive board completely eliminate the need for this circuit, instead of purchasing encoders with the analog output option?

**Comment by ericjunkins** [comment]
@lukeweston Have you looked at the electronics-pcb-rework branch? https://github.com/nasa-jpl/open-source-rover/tree/electronics-pcb-rework . This has implemented decoupling capacitors on the encoder lines. There are only 2 LM358 used correct, that is a typo in the BOM. 

As far as the voltage division I felt it was better to over divide the signal and take it to a 0-1.6V range and sacrifice a tiny bit of resolution to avoid any clipping issues. The angular resolution becomes 1 deg ~= 4.444 encoder ticks, which with filtering caps noise fluctuations are then on the +/- 0.5 deg, which we found more than acceptable for the project.

Having an absolute quadrature encoder would solve that yes, if you have any part suggestions feel free to make some suggestions. We thought that there is some benefit as a teaching project to not just have every item be plug-and-play, and provide some change to build some circuits and test/learn that as well.

Thanks for the questions!
