### ISSUE TITLE
Monolithic board Electrical Assembly Instructions errors

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#116]
Electrical Assembly Instructions OMITTED D1 and F1.
They're clearly installed in the photos, but no reference in the instructions.  
They're the last left-over parts and slots prior to placing the standoffs.

On the PCB J13 (GND +12V) is omitted from the instructions.
On the BOM, J13 is the 5.08mm 2P side entry terminal block.  
But that is too large for the holes which match the 3.5mm J6 for the Arduino shield
(not to be confused, but it is, with the J6-7 2x20 40P ribbon cable connectors.)
There are 3 slots on the PCB for the 5.08mm 2P connectors labeled J15 (BATTERY IN), J16 (POWER SWITCH) & again J16 (BATTERY OUT).
Not sure what this J13 is supposed to do, but one of the two 3.5cc 2P terminal blocks is going into it.

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

![44 fuse   diode](https://user-images.githubusercontent.com/35434147/57972107-e9064d80-795b-11e9-9f8c-9d8cd6db9753.JPG)
![40 this thing must go here](https://user-images.githubusercontent.com/35434147/57972027-1c94a800-795b-11e9-946f-fc5ed11aa037.JPG)
![41 J-whatever in place](https://user-images.githubusercontent.com/35434147/57972028-1c94a800-795b-11e9-8288-450f9a07d918.JPG)
![38 here is one J16](https://user-images.githubusercontent.com/35434147/57972025-1bfc1180-795b-11e9-800d-4a0530752c8d.JPG)
![39 and here is another](https://user-images.githubusercontent.com/35434147/57972026-1c94a800-795b-11e9-8737-389d479506f1.JPG)

**Comment by ericjunkins** [comment]
@JHPHELAN Sorry I Must have missed this issue. Solving this currently by adding the instructions for which piece goes here. It is just a breakout of the 12V regulator line. I'm sure you had figured that out by now.

**Comment by ericjunkins** [comment]
Fixed in commit 4b494c4
