### ISSUE TITLE
Monolithic board testing fails at step two!  Test pad T2 isn't GND

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#118]
**Electrical Assembly Instructions / 2 Component Integration and Testing / 
2.1 Power Distribution System:**

"1. Begin by powering the board. In order to do this we will be bypassing the switch and
volt meter, so this connection will look a little bit different than when you fully install
the board into the rover. Insert the red wire on the Tamiya Battery Connector E35
into the IN terminal on connector J16, and the black wire to the GND terminal on
the connector J15."

Do we _really_ want to connect the battery to two different terminal blocks, or is one of these a typo?  [apparently it DOES work once you realize that T2 is NOT ground but use the battery ground as reference]

![IMG_4816](https://user-images.githubusercontent.com/35434147/57972865-9a5db100-7965-11e9-9f1f-58cbe941072a.JPG)

"2. Using a Digital Multimeter (DMM) probe the voltage accross the test points T1 and
T2. These will tell you the voltage level that the board is at, which is the direct voltage
of the battery. Verify that from T1 to T2 reads a positive number, and is between 12V
and 16.7V depending on the charge state of your battery."

Doing this, there is NO voltage between T1 and T2 when voltage is present between the two wires.

Connecting the battery to the more logical terminals on J15 has a similar problem.  Even shorting the POWR SWITCH J16 terminals failed to produce a voltage.

![IMG_4817](https://user-images.githubusercontent.com/35434147/57972965-22908600-7967-11e9-9bcf-96a3a54fe8e2.JPG)
![IMG_4818](https://user-images.githubusercontent.com/35434147/57972967-26240d00-7967-11e9-89ca-2b9c34e13587.JPG)

Further continuity testing revealed that test pad **T2 DOES NOT CONNECT TO GROUND**.  All the other GND terminals on the board DO test as connecting to the GND terminal of BATTERY IN.  I got an error message trying to view the PCB in KiCAD so I can't trace the problem.  I'll have to skip this part and proceed under the assumption that T2 is mislabeled or not connected.  So far no mention in the directions about installing the 12V or 5V regulators so they are not installed at this point.

"INSERT IMAGE OF ROBOCLAW WITH WIRES IN IT AND ROBOCLAW CON-
NECTION TO BOARD"  Permission granted.

![IMG_4821 (Edited)](https://user-images.githubusercontent.com/35434147/57973946-2e377900-7976-11e9-8ef4-1ae705a5db69.JPG)

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

**Comment by ericjunkins** [comment]
I guess when I say "GND" yes this is being loose with the term "Ground". It refers to Battery Ground, or the (-) terminal of the battery. This is not Earth Ground.

Below shows the schematic of the board.
![image](https://user-images.githubusercontent.com/25470708/57975992-d22b1f80-798a-11e9-866b-467a797f9484.png)

I will have to dig in further to that test point, i'll try and verify with my boards.  What is the error message from KiCAD? I want to make sure people can view/edit these boards so I want to try and help fix that as well.

**Comment by JHPHELAN** [comment]
@ericjunkins 
I assumed that GND meant board GND / battery GND.  But T2 doesn't have continuity to  battery GND unlike every other GND designated terminal on the board.  However, if you ignore the problem with T2 and measure against any actual GND on the board, it measures ok so far as I've gotten.

The obviously old (as it bears little resemblance to yours) schematic I have (Monolithic Board.pdf) shows:
![Monolithic Board cropped](https://user-images.githubusercontent.com/35434147/57976491-512e5100-79a7-11e9-9b33-b9568539be79.jpg)

But I was less concerned about the labels as the actual board traces.  I may well be misusing KiCAD as I am not at all familiar with it, but when I tried to look at the actual construction of the PCB (Monolithic Board.pro) in KiCAD I got:
![Capture](https://user-images.githubusercontent.com/35434147/57976499-74590080-79a7-11e9-902f-d919f69441d9.PNG)

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

**Comment by JHPHELAN** [comment]
BTW, my teacher at TXRX makerspace for Python & OpenCV, Dan Mailman, taught us that documentation always takes a back seat to creation.  EXPECT that documentation will be incomplete, out of date and inaccurate.  Just be pleasantly surprised when it actually works as hoped, just like your program.  That attitude has saved me a LOT of frustration!
JHP

**Comment by ericjunkins** [comment]
@JHPHELAN I'm trying to close some of these open issues one by one here. I should expect that T2 is always GND for the system no matter what. Were you still seeing issues where it was not? I wouldn't expect that to happen and am just trying to check and see if this still needs to be an open issue or not.

**Comment by JHPHELAN** [comment]
On my board T2 did not connect to anything.  Continuity check between it and  any other GND tests OPEN.
JHP

**Comment by ericjunkins** [comment]
Ah okay, I found the error.. the following test point is not actually connected into the net.
![unconnected pin](https://user-images.githubusercontent.com/25470708/59170481-aca9b580-8af3-11e9-8108-01068a544e12.PNG)

leading to this via/net not being connected into the GND plane.
![unnamed net](https://user-images.githubusercontent.com/25470708/59170472-a9aec500-8af3-11e9-816a-c73389232d93.PNG)

Fixed here:

![named trace](https://user-images.githubusercontent.com/25470708/59170499-c519d000-8af3-11e9-9463-8495f469c72a.PNG)
