### ISSUE TITLE
M2A & M2B on the PCB are reversed vs the RoboClaw

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#119]
On the monolithic controller PCB, the labels for the terminal strips that jumper to the RoboClaw at M2A and M2B are **reversed**.  M2A is to the outside of the RoboClaw whereas the terminal strip outside connector is labeled M2B.  I hope it's just the labels that are backwards and not the internal wiring.  Else the wires between each RoboClaw and the PCB for M2 with have to be switched at one end.

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

![IMG_4822](https://user-images.githubusercontent.com/35434147/57974416-54ace280-797d-11e9-844e-432ce2ee6863.JPG)

**Comment by ericjunkins** [comment]
The motor terminals do not particularly make a difference which is which for A and B, you can reverse the polarity during calibration such that it applies voltage to make it correct for "forward" of the rover

**Comment by JHPHELAN** [comment]
All 5 RoboClaws power up!
JHP

![IMG_4823](https://user-images.githubusercontent.com/35434147/57974848-6b0a6c80-7984-11e9-84e8-02c91a55d9fb.JPG)

**Comment by ericjunkins** [comment]
Looks great! I do appreciate the feedback and pictures with your process putting this together. I know we released it at a very prototype-level stage and appreciate those of you who are helping test documents etc.

**Comment by JHPHELAN** [comment]
2.4:
"INSERT IMAGE OF ROBOCLAW WITH WIRES IN IT AND ROBOCLAW 
CONNECTION TO BOARD"

Permission granted.
Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

![IMG_4824](https://user-images.githubusercontent.com/35434147/57977222-79bf4680-79b9-11e9-8eab-054128dac168.JPG)

**Comment by vssystemluba** [comment]
Thanks for pointing this out.  Even though it will be calibrated either way, I went ahead and flipped the silk screen labels (d2542d7) to keep others from getting confused.
