### ISSUE TITLE
Electrical Assembly Instructions omit OpAmps until corner motors fail

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#124]
Electrical Assembly Instructions 2.3.3 
"...If that is not recheck that the OP-amp is installed in the correct direction."
There is no mention of the Op-Amps prior to this.  I assume they should be installed after the sockets for them?  Note that the key notch on the chip should match the key notch on the socket which, contrary to the directions, DOES matter which way it goes in if this convention is to work.

![IMG_4827 (2)](https://user-images.githubusercontent.com/35434147/57985510-921d7880-7a2e-11e9-881a-e957b89a5dbd.JPG)

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

**Comment by ericjunkins** [comment]
Roger that, it should have had that step before then. That picture is the correct orientation. I actually did not realize the dip sockets had a notch, in practice you can put the dip socket in either direction but i'll make sure to note it should be this way.

**Comment by ericjunkins** [comment]
Fixed in commit 7c0e027
