### ISSUE TITLE
Change second image to RPI with ribbon cable and usb cable plugged in

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#126]
Electrical Assembly Instructions: "Change second image to RPI with ribbon cable and usb cable plugged in".
(Web pix are **dark**.  Will look normal if saved/opened on your computer)

Jim Phelan
Mars rover project lead
USAi Labs (formerly Houston Robotics)

![IMG_4848](https://user-images.githubusercontent.com/35434147/58290373-26654380-7d7f-11e9-9d04-afff47366a37.JPG)

![IMG_4847](https://user-images.githubusercontent.com/35434147/58290391-32e99c00-7d7f-11e9-80c2-6c66b412e440.JPG)

**Comment by JHPHELAN** [comment]
Ordering a MUCH shorter 7" USB-micro USB cable for R Pi power.
BTW the lighted push-button power switch is:
![GPB553B2L01BR_sml](https://user-images.githubusercontent.com/35434147/58290866-d9826c80-7d80-11e9-917e-7b3e6d0fb344.jpg)

[https://www.digikey.com/products/en?keywords=GPB553B2L01BR](url)
JHP

**Comment by billydelectronics** [comment]
I found a USB A to USB Micro 90 6" cable on Amazon that works SLICK for the Monolithic PCB to RPI power: https://www.amazon.com/gp/product/B00S8GU03A/ref=crt_ewc_img_dp_2?ie=UTF8&psc=1&smid=A1AMUYYA3CT6HJ  ASIN: B00S8GU03A
![20190608_113814](https://user-images.githubusercontent.com/51517163/59151433-f016fd80-89e7-11e9-8625-8b27fa951efb.jpg)

BillyD

**Comment by ericjunkins** [comment]
Fixed in commit 7c0e027
