### ISSUE TITLE
3D printed battery holder doesn't fit battery

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#127]
Just printed the battery holder but find it doesn't fit.  Has anybody else tried this?  Made a fix?
JHP

![IMG_4879](https://user-images.githubusercontent.com/35434147/59150643-04f59000-89ec-11e9-8e8c-4edde1417073.JPG)

**Comment by ericjunkins** [comment]
oh, I forgot that I have a slightly higher capacity battery in mine so it is a bigger battery. Can you measure the dimensions of the battery and I can give you an updated part for it?

**Comment by JHPHELAN** [comment]
@ericjunkins 
[https://www.batteryspace.com/li-ion-battery-14-8v-5-2ah-77wh-8a-rate-for-diving-light---un-38-3-passed.aspx](url)
"Dimensions  1.6"(43mm) H x 1.6"(43mm) W x   5.5 "L(139mm)"
I measure from the 2 flat sides, avoiding the bumpy wire, side **1 15/32"** a little less than the specs.
If the top of the holder were lowered to an inside jaws clearance of 1 15/32" it would be good.

JHP

**Comment by ericjunkins** [comment]
yeah the dimensions of the datasheet aren't usually quite correct for these, they tend to be a bit bumpy and differently shaped. I'll upload a fix of that part

**Comment by JHPHELAN** [comment]
@ericjunkins BTW the bottom holes are too big for 4-40 and just a little small for the 6-32 heat set inserts.
The 6-32 would probably melt its was in but the narrow end wouldn't have a clean start.
JHP

**Comment by ericjunkins** [comment]
I've had no issues putting #6-32 heat set inserts in these parts

**Comment by ericjunkins** [comment]
@JHPHELAN I finally got around to making edits of this for the 5.2mAH battery size. Can you let me know if this fits well or if it needs tuning still? It can be found at https://github.com/nasa-jpl/open-source-rover/blob/electronics-pcb-rework/Optional%20CAD%20parts/STL/battery%20holder_5_2maH.STL

**Comment by ericjunkins** [comment]
My part for the test fit of this can be seen below:

![battery_holder_pic](https://user-images.githubusercontent.com/25470708/60042518-c1995380-9672-11e9-8fa9-d3debe4ae004.jpg)

I believe this fixes this issue and will close it based on commit b441a83c82498513b61260dd79068bb3b2afc41f
