### ISSUE TITLE
osr-ROS Software Install instructions missing step

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#132]
Section 1.5 Building the Rover Code to work with your ROS installation
"Move to the directory containing the main OSR logic:"
     cd /home/pi/osr/ROS
"Create a catkin workspace directory: (read more here):"
     mkdir /home/pi/catkin ws
"Copy the source files to your catkin workspace:"
     ~/osr/ROS$ mv led screen/ osr/ osr bringup/ osr msgs/ src
     mv: target 'src' is not a directory
you have to specify the catkin_ws/src as the target:
     mv led screen/ osr/ osr bringup/ osr msgs/ ~/catkin_ws/src

(~ = home/pi in Raspbian speak)
JHP

**Comment by vssystemluba** [comment]
Sorry about the confusion.  I just pushed updated docs that include that missing step.
