### ISSUE TITLE
Add wording for install of ros desktop full version

### ISSUE THREAD

**Issue by vssystemluba** [nasa-jpl/open-source-rover#136]

**Comment by vssystemluba** [comment]
(as per the discussion on the OSR forum at https://www.tapatalk.com/groups/jpl_opensource_rover/viewtopic.php?p=792#p792)

**Comment by vssystemluba** [comment]
We may also alternatively just recommend downloading a pre-built image that we supply for Stretch / ROS.

**Comment by vssystemluba** [comment]
Also add clarity about WHICH version of Raspbian to install, since the installation process is definitely trickier in Buster.

Also add a link to the existing image for those who don't want to / can't build their own image.

**Comment by JHPHELAN** [comment]
The Software Steps directions to refer to the ROS.org instructions need clarification.  There are several choices of which version of ROS to install desktop-full, desktop, ros-comm, etc.  Which one should we install?  There were also missing packages, ie joy that need to be installed with the main install.  We need a full walk-through of the ROS install.
JHP

**Comment by ericjunkins** [comment]
It's ros desktop full. It has joy package included, it was verified that worked and was included in our install a few days ago

**Comment by JHPHELAN** [comment]
pi@Fidelity:~ $ cd ros_catkin_ws/
pi@Fidelity:~/ros_catkin_ws $ rosinstall_generator desktop-full --rosdistro kinetic --deps --wet-only --tar > kinetic-desktop-full-wet.rosinstall
**The following unreleased packages/stacks will be ignored: desktop-full
No packages/stacks left after ignoring unreleased**
JHP
USAi Labs

**Comment by JHPHELAN** [comment]
The ROS install refers to:
http://www.ros.org/reps/rep-0131.html#variants which is old ROS groovy variants
the current rep is:
http://www.ros.org/reps/rep-0142.html which is indigo and newer.
apparently, between the two, desktop-full became desktop_full  [hyphen to underscore]!
JHP
USAi Labs

**Comment by ericjunkins** [comment]
reasons like that above are why we don't want to spell out individual every step-by-step for the ROS install, and rather link to the maintained ROS install guides. Things are bound to change with their stuff and it's much easier to go to their pages and learn whats wrong

**Comment by JHPHELAN** [comment]
We should at least specify "desktop_full", show the correct command to execute it and point out pitfalls in linked directions when we are aware of them.
JHP

**Comment by ericjunkins** [comment]
agreed, will update wording

**Comment by JHPHELAN** [comment]
Here's another critical bit of info -- ROS changed their GPG keys as of 6/7/19.  The ROS install instructions are not updated and will not work unless you get the new keys.  I think this is why my last attempt to build ROS from source failed.  The OSR Software Steps should point this out.  If we ever get a proven road map we'll share.
JHP
USAi Labs
[https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454](url)

**Comment by timsent** [comment]
Leo and I are trying to build it this evening. Thanks for letting us know!

**Comment by vssystemluba** [comment]
@JHPHELAN thanks for the follow-up.  I've added a section in the Software Steps doc highlighting the known "gotchas", as well as indicating that you should be installing/building the desktop_full version.
