### ISSUE TITLE
Incorrect Instructions in Software Steps.pdf

### ISSUE THREAD

**Issue by camm73** [nasa-jpl/open-source-rover#137]
In section 1.5, the very last command currently says `sudo nano /.bashrc`, however this is not in the proper directory. Should be changed to `sudo nano ~/.bashrc`.

Also before moving the the files in the from the cloned repo to the "orc_ws" workspace in section 1.5, the python files must be made executable, or else they will cause an error. This can be done be running `cd /home/pi/orc/ROS/scripts` and then running `chmod +x <insert python script filename>` for each of the python scripts.

**Comment by JHPHELAN** [comment]
@camm73 You are correct!  Note typo - "orc_ws" should be "osr_ws"
JHP

**Comment by ericjunkins** [comment]
I don't know I rather like the idea of the orc workspace

![fj5gxeeyj0py](https://user-images.githubusercontent.com/25470708/61902650-66f45100-aed7-11e9-9b18-7de3a379c6a8.jpg)
