### ISSUE TITLE
Fix inconsistency in Rocker Bogie between CAD and mechanical build doc (figure 6)

### ISSUE THREAD

**Issue by vssystemluba** [nasa-jpl/open-source-rover#139]
See https://www.tapatalk.com/groups/jpl_opensource_rover/boulder-team-build-t121.html#p826 for details.  The build doc shows a 4-hole U channel (3.75"), but the CAD shows a 3-hole U channel (3").

**Comment by ericjunkins** [comment]
Fixed in commit 78080c8dbf8386d2dc5a20e96042b81f55918533
