### ISSUE TITLE
Add photos of cable connections in Electrical Build.pdf

### ISSUE THREAD

**Issue by mikcox** [nasa-jpl/open-source-rover#140]
![image](https://user-images.githubusercontent.com/2334865/61967939-89e03d00-af8b-11e9-9b28-6191f48a8262.png)

**Comment by mikcox** [comment]
Note: Steps 2 and 3 above have been removed since they are duplicated in the PCB assembly document.

**Comment by Achllle** [comment]
Solved with the new [wiring instructions](https://github.com/nasa-jpl/open-source-rover/tree/master/electrical/wiring)!
