### ISSUE TITLE
Are the T6 standoffs the incorrect side in the parts list?

### ISSUE THREAD

**Issue by toebes** [nasa-jpl/open-source-rover#143]
The master parts list shows T6 as a 4-40 x 3/4 Threaded Standoff [https://www.mcmaster.com/91780A166].  However when assembled in the model, the voltage regulators are unable to reach the plug to connect.  Furthermore given that the board is mounted with the T3 standoffs which are also 3/4", the T6 spacers would be making contact with the top of the case along with the T3 standoffs, also eliminating any possibility of mounting the voltage regulators on top of it.  If you look in the OnShape model, you can see the voltage regulators intersecting with the top plate.

**Comment by ericjunkins** [comment]
@toebes I have fixed the reference mistake in the documentation, which called for standoff T6 instead of T8, which is a 1/2 in long 2-56 standoff. This should solve both issues you brought up here.

On a related note the OnShape of the electronics looks amazing, really good job on that!
