### ISSUE TITLE
Video demo

### ISSUE THREAD

**Issue by Dmole** [nasa-jpl/open-source-rover#15]
A Youtube demo of base model capabilities would help clarify specifications and popularise the project.

**Comment by townie** [comment]
Video would be great for getting an idea of sound profile for the motors and drive system

**Comment by Dmole** [comment]
Like we know it's 10x slower than walking speed, but just show us :)

**Comment by townie** [comment]
HAHA! Yes (https://github.com/nasa-jpl/open-source-rover/issues/15#issuecomment-410811589). I did the math on it as soon as I read the spec sheet 

Rover Max speed | 6.7 [in/s]
-- | --

Vs

Human walks speed | 55 [in/s]
-- | --

**Comment by ericjunkins** [comment]
We'll post some videos of it in driving around/over obstacles soon! 

(For frame of reference here this article talks about Curiousity's first year on Mars and it's speed etc https://www.space.com/22226-mars-rover-curiosity-time-lapse-video.html )

**Comment by vssystemluba** [comment]
Behold... videos!!!  😄 

An intro video we used to promote the rover internally at JPL that was cleared for external release.  Note that the obstacles in this video are in the "cute" category; the rover could conquer MUCH larger obstacles than those in this video.
https://flic.kr/p/NV5Y5E

Quick video of the rover easily conquering a pile of rocks (note that the rover can still climb obstacles more aggressive than this):
https://flic.kr/p/29XdYod

...and another video of a cinderblock stair test we did to see whether the rover could conquer a specific difficult geometry (it didn't _quite_ get all the "stairs", but it would've easily climbed over the first one which is nearly 2x the height of the wheel):
https://flic.kr/p/28hM3bN
