### ISSUE TITLE
Step 2.4.7 of the Body Assembly instructions places the Battery holder over the hole for the Rocker-Bogie Rod

### ISSUE THREAD

**Issue by toebes** [nasa-jpl/open-source-rover#150]
Step 2.4.7 of the Body Assembly instructions has you place one of the battery clamps on the side wall in the middle of the plate.  In this position it is covering up both middle holes on the side plate.    However when you get to Step 1.4 (5) in the Mechanical Integration which instruct placing the aluminum rod S16A through the side plates, the rod intersects with the battery clamp.

**Comment by vssystemluba** [comment]
I've updated the CAD in the OnShape model to correctly place the battery holders:

![image](https://user-images.githubusercontent.com/2334865/62578951-4f15b900-b857-11e9-9326-47df0e15965c.png)


I've also updated the images in the Body Build Doc to reflect the proper placement.  Thanks for pointing this out.
