### ISSUE TITLE
Update prices and misc. fixes to master parts list

### ISSUE THREAD

**Issue by Roger-random** [nasa-jpl/open-source-rover#160]
Offering to update ```master_parts_list.xlsx``` to reflect price as of September 2019. The prices were never guaranteed to be 100% accurate, but it shouldn't hurt to update as we go.

Since a xlsx file does not present neat deltas in Github, the changes will be spelled out in this issue individually. Once all parts have been ordered and prices updated, I plan to create a single pull request incorporating all changes.

**Non-pricing updates:**

- B13 item number off by one. Should be 91255A077 not 91255A076
- S9 missing item number in column E. Filling in 555174

**Price updates:**

_McMaster-Carr:_
- B8 was $2.87 now $3.02
- S16 was $23.16 now $25.74
- S29 was $4.92 now $5.28
- W3 was $2.47 now $2.59
- T7 was $0.48 now $0.64
- T8 was $0.96 now $1.00

_ServoCity:_
- S18 was $2.09 now $2.19
- S19 was $1.49 now $1.59
- S22 was $2.26 now $4.99
- S25 was $5.99 now $6.99
- S26 was $3.69 now $5.20
- S7 was $2.79 now $2.89
- S8 was $1.29 now $1.49
- T3 was $1.79 now $1.89
- T9 was $3.29 now $3.39

**Comment by ericjunkins** [comment]
Thanks for the update on the price changes, we weren't aware of that. The parts list is generated programmatically now, quantities pulled from the build documents and references for links and prices is in /parts_list/master_parts_list_raw.csv, so any changes should be made there

**Comment by mikcox** [comment]
Thanks for the detailed notes, Roger!  I've updated the pricing in the commit above.

...sad to see that none of the prices are going _down_...
