### ISSUE TITLE
PCB Assembly: 1.1.9 Table 10 standoff inconsistencies

### ISSUE THREAD

**Issue by Roger-random** [nasa-jpl/open-source-rover#162]
There are some inconsistencies in PCB Assembly document 1.1.9 regarding standoffs used.

**RoboClaw standoff**

In table 10, it lists part T11 as 4-40 x 1/2" threaded standoff. 20 of them are used, 4 per RoboClaw x 5 RoboClaws.

In the CSV under /parts_list/, T11 is listed as 2-56 x 1/2" threaded standoff quantity 20. The documents here does have 4-40 x 1/2" but it is called T5 and only quantity of 1 is specified.

Suggestion: Change document reference from T11 to T5. Change parts_list quantity for T5 from 1 to 20. See next item for more on T11.

**Voltage regulator standoffs**

In table 10, it lists part T8, 2-56 x 1/2" for voltage regulators.

Under /parts_list/ T8 is 2-56 x 3/8". T11 is the 2-56 x 1/2" standoff, see above issue.

Due to above issue, we have plenty of 2-56 x 1/2" to spare.

3/8" is slightly too short. 1/2" is slightly too long but it appears to make sufficient electrical connector to function.

Suggestion: Change document reference from T8 to T11. 
Alternate suggestion: add new part for standoff 2-56 x 7/16" long.

**Comment by dcschooley** [comment]
Pull request #293 fixes the RoboClaw standoff discrepancy. Not touching the voltage regulator issue into correct size can be confirmed.
