### ISSUE TITLE
Main PCB: Potential collision RoboClaw 1 and C2

### ISSUE THREAD

**Issue by Roger-random** [nasa-jpl/open-source-rover#169]
Using mainboard Rev E.

Our five RoboClaw controllers are mounted with the tops of their electrolytic capacitors flush against the main board. On RoboClaw 2-5, they meet up with flat uninterrupted PCB. In Rev E, however, capacitor C2 is directly on the other side of RoboClaw 1's capacitors. Its soldering points can barely clear in between two capacitor cans of RoboClaw 1. And this is when trimmed back almost flush.

If someone has a large solder joint that hasn't been trimmed, doesn't notice the potential for collision, and crank the screws tight while installing their RoboClaw 1, they risk puncturing the electrolytics.

Consider moving C2 to reduce the chance for this potential problem.

**Comment by apollokit** [comment]
Handled in https://github.com/nasa-jpl/open-source-rover/pull/198
