### ISSUE TITLE
Electrical Build doc: Inconsistent wire gauge X1, X2. 16 or 20 AWG?

### ISSUE THREAD

**Issue by Roger-random** [nasa-jpl/open-source-rover#170]
In Electrical Build.pdf:

Table 1 parts to build battery connector lists X1 (red) and X2 (black) as 16 AWG wires.

Table 3 in the same document lists X1 and X2 as 20 AWG wires.

Parts list describe X1/X2 as 20 AWG wires and that's what I purchased.

If table 1 is incorrect and we're supposed to use 20 AWG wires for battery, the typical guidance for wires recommend not to exceed 5A for 20 AWG. 20 AWG wires may burn up before tripping the 10A fuse.

If table 1 is correct and Table 3+parts list is wrong, 16 AWG is awfully thick to route through rover suspension for motors.

Perhaps the wires of table 1 and 3 are intended to be different wires of different gauge?

**Comment by Achllle** [comment]
The battery wires should definitely be at least 16AWG but I'd propose to even go to 12AWG which should be able to handle around 30A. When all motors are accelerating at the same time (corner + drive), we could easily hit such a value.
@ericjunkins does that sound reasonable to you? What kind of current can the PCB handle?

**Comment by apollokit** [comment]
Update:

the table 1 referred to above is now table 3 in [this subsection](https://github.com/nasa-jpl/open-source-rover/blob/master/electrical/electrical_build.md#21-switch-volt-meter-and-control-board) 

the table 3 referred to above is now table 6 in [this subsection](https://github.com/nasa-jpl/open-source-rover/blob/master/electrical/electrical_build.md#4-connecting-motors-and-encoders) 

Agreed that the wires of table 3 and 6 are meant to be different. The X1 and X2 designators are incorrect in table 3.

Seems like, per @Achllle 's proposal, we should use 12 AWG for the battery connections, and update table 3 and the parts list accordingly.

@Achllle, @ericjunkins , sound good?

**Comment by Achllle** [comment]
Sounds good to me; it's what I currently use and I don't find the wires to be too thick to work with. I'll let @dcschooley or @ericjunkins decide if that's too much.

**Comment by dcschooley** [comment]
12AWG is only too much if is too big for the terminal blocks. That size is a waste of copper for those short connections however.

**Comment by ericjunkins** [comment]
Has anyone tried to plug 12 AWG into the roboclaw terminal blocks? It sounds like thats the proposal? that seems hard to work with for those connections

**Comment by Achllle** [comment]
Yes, I have. It works but it is on the bigger size. I think if 14 or 16 AWG is safe and can deliver the power we should use that.

**Comment by ericjunkins** [comment]
I mean i use 20 AWG on mine so Anything is probably going to be fine. The wires are all such short distances it barely matters

**Comment by dcschooley** [comment]
If the wire is too big, there is a risk of some the strands not making it into the hole and ending up somewhere they don't belong. The difference between 12AWG and 16AWG in voltage drop across 1ft of wire is somewhere around 5mV at 10A. 18AWG vs. 12AWG is 9mV. 20AWG vs. 12AWG is about 17mV. Pulling 10A in a single motor wire or into a single RoboClaw will almost never happen, and if it does, it won't be for very long. There is no good reason for anything over 16AWG. 20AWG is fine. 18AWG is probably optimum.

**Comment by apollokit** [comment]
A'ight, 16AWG for the battery connections. Need to update the parts list and instructions accordingly
