### ISSUE TITLE
Rover 6" PVC Neck Too Long For Cable E26

### ISSUE THREAD

**Issue by Roger-random** [nasa-jpl/open-source-rover#172]
(Related issue: #168) 

Head Assembly Build PDF, section 3.1:

> You can make your rover's neck as long as you'd like, but for reference we cut our "neck" PVC pipe to be roughly 6 inches long.

The neck is actually constrained by the length of cable (E26) connecting main board to Arduino shield, which is 12 inches (~300mm) long.

In the first iteration I cut a 7-inch long PVC pipe. I found the cable could not reach its connector.

![Rover head cable could not reach](https://user-images.githubusercontent.com/8559196/64995476-30600480-d890-11e9-84aa-052915066714.jpg)

With a 5 inch (~128 cm) length of pipe, the cable could reach, but only barely which places a lot of stress on cable and connectors.

It is far better to cut PVC down to 4.5 inch (~115mm) for some slack and reduce tension.

![Rover head cable connected](https://user-images.githubusercontent.com/8559196/64995484-3655e580-d890-11e9-8b94-4217b44c8527.jpg)

Alternate solution: order a longer cable E26. See also related issue #168

**Comment by aktfire747** [comment]
It is far better to cut PVC down to 4.5 inch (~115cm) for some slack and reduce tension.

Btw 4.5 inches is 11.43 cm, not 115 cm. The dot makes all the difference. Same with accuracy of conversion of imperial to metric and vice versa. :)

**Comment by Roger-random** [comment]
Good catch on my typo! I was debating whether to put down 115mm or 11.5cm and ended up with 115cm which is not a satisfactory compromise between the two options. I'll edit the original text.

**Comment by mikcox** [comment]
I've updated our language in the build documents to specify a neck length of 4.5 inches.

Thanks for bringing this to our attention!
