### ISSUE TITLE
Drive motor gear breaking

### ISSUE THREAD

**Issue by jroanhorse** [nasa-jpl/open-source-rover#178]
Were having an issue where when we pick up the rover and place back down, the drive motors stop working. The motor is giving power, but the gears inside the motor don't work anymore. We think maybe there is added stress to the shaft from the motor attached to the wheel base. Would pulling back the drive motor be a good idea? Has anyone else come across this issue?

![IMG_0052](https://user-images.githubusercontent.com/55846040/66064043-e585f400-e501-11e9-9149-7be3280b4528.jpg)

Rough draft of pulling the drive motor back. 

![IMG_3318](https://user-images.githubusercontent.com/55846040/66064052-e9197b00-e501-11e9-99c3-fe1c728ac61f.JPG)

**Comment by ericjunkins** [comment]
I'll refer you to the discussion on the forum about this

https://www.tapatalk.com/groups/jpl_opensource_rover/motor-troubles-t127-s50.html
