### ISSUE TITLE
Question about design

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/open-source-rover#181]
Hi! I tried making an account on the Tapatalk forum to post this question but it just wouldn't let me so posting here, hope that's ok.

I'm considering building a rover too and was curious about two design decisions:

1. It seems like the front of the robot is different from the actual Mars Curiosity rover, i.e. the rocker and bogie are flipped. Does this make a difference and is there a reason for that? I couldn't seem to find an explanation anywhere.
2. What are the advantages of using corner steering versus skid steering for a smaller scale robot like this? Dropping them would lower complexity, price, weight and build time, and increase reliability.

Thanks!

**Comment by mikcox** [comment]
Thanks for reaching out!  That said, you're right... the forum is indeed a better place for questions like this.

There's some discussion on 1. at https://www.tapatalk.com/groups/jpl_opensource_rover/question-about-mechanical-design-jumpy-front-wheel-t11.html.  Basically, the real rover is actually optimized to drive backwards better than it drives forwards.  This means we can ALWAYS back out if we get stuck driving into some scary terrain.

On 2, one of our original requirements for the Open Source Rover was that it employed corner steering and mimicked the drive system of the real Mars rovers.  We agree that it'd be cheaper to use tank / skid steering, but it's not something we wanted to do for this project.  If you want to contribute a version that uses skid steering, we're all ears.  :)
