### ISSUE TITLE
Init Script errors

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#183]
**Software Steps 2.7 Init Scipts.**
This section says to:
     cd /home/pi/osr/Initn Scripts
     sudo cp LaunchOSR.sh /usr/bin/LaunchOSR.sh
     sudo chmod +x /usr/bin/LaunchOSR.sh
     sudo cp osr startup.service /etc/systemd/system/osr_startup.service
     sudo chmod 644 /etc/systemd/system/osr_startup.service

**/usr/bin/LaunchOSR.sh**
#!/bin/bash
bash -c ". /home/pi/osr_ws/devel/setup.sh"
bash -c ". /home/pi/osr_ws/devel/setup.bash"
bash -c ". /opt/ros/kinetic/setup.sh"
bash -c ". /opt/ros/kinetic/setup.bash"
bash -i -c "roslaunch osr_bringup osr.launch"

**osr_startup.service** _example from OSR Github_:
[Unit]
Description=OSR service
After=network.target

[Service]
User=ubuntu
Group=ubuntu
WorkingDirectory=/home/ubuntu/LaunchOSR.sh
ExecStart=/home/ubuntu/
ExecReload=/bin/kill -HUP $MAINPID
Restart=always

RestartSec=3

[Install]
Wantedby=multi-user.target

**_Translating this from Ubuntu to Raspbian:_**
**/etc/systemd/system/osr_startup.service**
[Unit]
Description=OSR service
After=network.target
[Service]
User=pi
Group=pi
#WorkingDirectory=/usr/pi/LaunchOSR.sh 
#This line is wrong. It doesn't point to a directory but to a file. It should be:
WorkingDirectory=/home/pi/
#Same for below.  The filename was missing:
ExecStart=/usr/bin/LaunchOSR.sh
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=3
[Install]
Wantedby=multi-user.target

This configuration works fine (after correcting the error above thanks to Antonio from our group)
for start, stop, and status of osr_startup.service
BUT if I try 
**sudo systemctl _enable_ osr startup.service**
in order for the system to launch on power-on
I get the following error:
**pi@Fidelity:~ $ sudo systemctl enable osr_startup.service**
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.

the WantedBy file referenced does exist in the directory.

The Linode.com link provides only a rudimentary example or a useless encyclopedia of documentation.
I don't see any mention of this problem here or in the TapaTalk.
Perhaps no one else has tried launch on power-up?

Jim Phelan
USAi Labs

**Comment by JHPHELAN** [comment]
Antonio comes through again:

Hi Jim,
The only issue I see, and it makes sense that it does not want to be enabled is the last line of the systemd file,
"Wantedby=multi-user.target"  should be "WantedBy=multi-user.target" 
Basically WantedBy tells Linux if you load the multi-user.target also load this script/service.
Let me know if that helps.
Antonio

Capitalized the B in WantedBy and the error disappeared!
Another typo to fix in the documentation / sample code...

JHP

**Comment by Achllle** [comment]
Good catch, I also had to fix this. I'll create a PR for this soon.
Software related issues are a better fit for the [osr-rover-code](https://github.com/nasa-jpl/osr-rover-code) repo by the way. Documentation for the startup service should probably move to there as well.

**Comment by Achllle** [comment]
This has been fixed, please reopen on the osr-rover-code repository if the issue persists
