### ISSUE TITLE
AttributeError: Roboclaw instance has no attribute '_port'

### ISSUE THREAD

**Issue by jacknaish** [nasa-jpl/open-source-rover#188]
Hello,

I recently came across several challenges in the JPL OSR code that left me stumped for hours while attempting to run the code on the Rasberry Pi.

Below I detail these challenges and my solution to mitigate them. Hopefully they help someone else.
I'd be keen to discuss these solutions with people who ran into a similar problems. 

Cheers,
Jack

1. After following the JPL Rover software instillation steps found  [here](https://github.com/nasa-jpl/open-source-rover/blob/master/Software/Software%20Steps.pdf) you will run:
	```
	roslaunch osr_bringup osr.launch
	```
	
	and be greeted by the following error:
	
	```
	[ERROR] [1580268175.139144197]: Couldn't open joystick force feedback!
	[ INFO] [1580268175.145843295]: Opened joystick: /dev/input/js0. deadzone_: 0.050000.
	('Attempting to talk to motor controller', 128)
	Traceback (most recent call last):
	  File "/home/rover/osr_ws/src/osr/scripts/motor_controller.py", line 9, in <module>
	    motorcontrollers = MotorControllers()
	  File "/home/rover/osr_ws/src/osr/scripts/roboclaw_wrapper.py", line 42, in __init__
	    version = version & self.rc.ReadVersion(address)[0]
	  File "/home/rover/osr_ws/src/osr/scripts/roboclaw.py", line 708, in ReadVersion
	    self._port.flushInput()
	AttributeError: Roboclaw instance has no attribute '_port'
	```
	
	To get around this goto line 1066 of roboclaw.py

	**Replace**
	```
	def Open(self):
			try:
				self._port = serial.Serial(port=self.comport, baudrate=self.rate, timeout=1, interCharTimeout=self.timeout)
			except:
				return 0
			return 1
	```
	**With :**

	```
	def Open(self):
			self._port = serial.Serial(port=self.comport, baudrate=self.rate, timeout=1, interCharTimeout=self.timeout)
	```
		
2. In replacing the above try - except block we expose a stack trace that was previosuly being dissolved. We can view the real error if we re-run:
	```
	roslaunch osr_bringup osr.launch
	```
	And it will become clear that the true problem is a permissions error:
```
		Traceback (most recent call last):
	  File "/home/rover/osr_ws/src/osr/scripts/motor_controller.py", line 9, in <module>
	    motorcontrollers = MotorControllers()
	  File "/home/rover/osr_ws/src/osr/scripts/roboclaw_wrapper.py", line 29, in __init__
	    self.rc.Open()
	  File "/home/rover/osr_ws/src/osr/scripts/roboclaw.py", line 1067, in Open
	    self._port = serial.Serial(port=self.comport, baudrate=self.rate, timeout=1, interCharTimeout=self.timeout)
	  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 240, in __init__
	    self.open()
	  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 268, in open
	    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
	serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyAMA0: [Errno 13] Permission denied: '/dev/ttyAMA0'
	[motor_controller-2] process has died [pid 3303, exit code 1, cmd /home/rover/osr_ws/src/osr/scripts/motor_controller.py __name:=motor_controller __log:=/home/rover/.ros/log/e97bb840-4246-11ea-922b-b827eb670d1c/motor_controller-2.log].
	log file: /home/rover/.ros/log/e97bb840-4246-11ea-922b-b827eb670d1c/motor_controller-2*.log
```
3. This then gives us a clue as to the next solution. We can mitigate this permissions error by adding the user to the sudo dialout group:
		**Option 1)**
	```
	sudo adduser YOUR_PI_NAME_HERE dialout
	```
	**Option 2)**
	If that does not work you can use a temporary solution that will only last the current session. 
	```
	sudo chmod 666 /dev/ttyAMA0
	sudo chmod 666 /dev/ttyS0
	```
	Regardless of either option you must reboot your pi for changes to take effect. 
4. Now to test everything is fully working you can type:
	```
	roslaunch osr_bringup osr.launch
	```
	And you should see:
	```
	[ INFO] [1580330011.140342626]: Opened joystick: /dev/input/js0.  
	deadzone_: 0.050000.  
	('Attempting to talk to motor controller', 128)  
	('Attempting to talk to motor controller', 129)  
	('Attempting to talk to motor controller', 130)  
	('Attempting to talk to motor controller', 131)  
	('Attempting to talk to motor controller', 132)  
	[Motor__init__] Sucessfully connected to RoboClaw motor controllers  
	[INFO] [1580330012.391775]: Starting the rover node  
	[INFO] [1580330012.644913]: joystick started
	```
	The rover should now be controllable by the X-Box 360 joysticks :)

**Comment by ericjunkins** [comment]
I have to point out that this is not a bug in the software. By default the user "pi" should have permissions to the group dialout, though maybe not depending on what version of OS you install. We could turn this issue into a pull request to add a command to do `sudo addusr <user> dialout` to the software steps, however there is no software bug here.
