### ISSUE TITLE
Max current for roboclaws should be set at 15A

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/open-source-rover#194]
Roboclaw recommends setting the max current to the actual maximum for that roboclaw. In case of the 2x7A the peak per channel current is 15A. When that current is set to a value that is too low, weird stuff starts to happen (MBH error gets triggered). The roboclaw protects itself from overcurrent regardless of that setting.

**Comment by apollokit** [comment]
@ericjunkins how is this related to the pcb revision? Is it a problem with the size of the traces or something?

**Comment by apollokit** [comment]
after talking to @ericjunkins, this isn't pcb revision related
