### ISSUE TITLE
Use tables instead of images for lists of required parts in build documents

### ISSUE THREAD

**Issue by vssystemluba** [nasa-jpl/open-source-rover#20]
As reported by @xtream1101, our "required parts" tables in the subassemblies are images rather than tables.  Tables will be easier to consume via copy/paste and will be easier to modify in the future as the required parts change.

**Comment by xtream1101** [comment]
I will work on this. Can't assignee myself to this though.

**Comment by ericjunkins** [comment]
I agree it would be easier to have them as tables instead of just images. I think my one statement about this is I would want to preserve having a graphical image of each of the parts being used then I think this would be great!
