### ISSUE TITLE
init script directory does not exist for Ubuntu 18.04

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#209]
Software Steps 
Rover Code Bringup
"2 Automatic bringup with init script"
...
"There are two scripts in the ”Software/Init Scripts” folder. The first is the bash file that runs the roslaunch file, and the other creates a system service to start that bash script. Open up a terminal on the raspberry Pi and execute the following commands."

cd /home/pi/osr/Init\ Scripts                    
**This directory does not exist in Ubuntu setup**
sudo cp LaunchOSR.sh /usr/bin/LaunchOSR.sh
sudo chmod +x /usr/bin/LaunchOSR.sh
sudo cp osr_startup.service /etc/systemd/system/osr_startup.service
sudo chmod 644 /etc/systemd/system/osr_startup.service

**Comment by Achllle** [comment]
Hi @JHPHELAN, this is the wrong repository for this issue. This repository (`open-source-rover`) contains all the files to build the rover. The [`osr-rover-code` repository](https://github.com/nasa-jpl/osr-rover-code) contains the code to run the rover as well as instructions for running the code, which also contains the instructions you are referring to.  Please reopen your issue on the other repository, and if you could also clarify which directory does not exist (your comment may refer to the line above or below), we will be happy to help you there!
