### ISSUE TITLE
Port Software Controls doc to markdown

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#212]
The [Software Controls](https://github.com/nasa-jpl/open-source-rover/blob/master/Software/Software%20Controls.pdf) doc should be ported to markdown and moved to the [rover code](https://github.com/nasa-jpl/osr-rover-code) repo.

**Comment by SConaway** [comment]
Making a sample comment per https://github.com/nasa-jpl/open-source-rover/issues/202#issuecomment-708590686.

I can do this over / by the weekend if you want, just let me know.

**Comment by apollokit** [comment]
Sweet, got you assigned. 

No rush on this. Sometime in the next few weeks, it's not pressing. I'm thinking something like a 2 or 3-month time span for all the docs.

**Comment by Achllle** [comment]
TBH I might be the one to do this, @apollokit . The current instructions do not reflect the actual controls.

**Comment by SConaway** [comment]
Good idea. I don't want to waste my time and then have it all get redone

**Comment by apollokit** [comment]
Sounds good, reassigned.

**Comment by Achllle** [comment]
I made a [separate issue](https://github.com/nasa-jpl/osr-rover-code/issues/127) in the code repo to add the documentation from here. Once that's done, this can be deleted. For now it's not in anyone's way and it's clearly stated that the document is outdated.
