### ISSUE TITLE
Port Head Assembly Build Doc to markdown

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#217]
The [doc](https://github.com/nasa-jpl/open-source-rover/blob/master/Mechanical/Head%20Assembly/Head%20Assembly%20Build%20Doc.pdf) to be ported

Refer to [the project](https://github.com/nasa-jpl/open-source-rover/projects/1) for context

**Comment by SConaway** [comment]
Commenting as requested by @apollokit

**Comment by apollokit** [comment]
Assigned!

**Comment by apollokit** [comment]
Done, on https://github.com/nasa-jpl/open-source-rover/pull/247
