### ISSUE TITLE
Port Mechanical Integration Build Doc to markdown

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#218]
The [doc](https://github.com/nasa-jpl/open-source-rover/blob/master/Mechanical/Mechanical%20Integration/Mechanical%20Integration%20Build%20Doc.pdf) to be ported

Refer to [the project](https://github.com/nasa-jpl/open-source-rover/projects/1) for context

**Comment by dcschooley** [comment]
Working on it.

**Comment by dcschooley** [comment]
completed

**Comment by apollokit** [comment]
https://github.com/nasa-jpl/open-source-rover/pull/248
