### ISSUE TITLE
Port Electrical Calibration doc to markdown

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#220]
The [doc](https://github.com/nasa-jpl/open-source-rover/blob/master/Electrical/Calibration.pdf) to be ported

Refer to [the project](https://github.com/nasa-jpl/open-source-rover/projects/1) for context

**Comment by dcschooley** [comment]
I'm all over this one.

**Comment by dcschooley** [comment]
completed

**Comment by apollokit** [comment]
This is on https://github.com/nasa-jpl/open-source-rover/pull/245
