### ISSUE TITLE
Port Electrical Build doc to markdown

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#221]
The [doc](https://github.com/nasa-jpl/open-source-rover/blob/master/Electrical/Electrical%20Build.pdf) to be ported

Refer to [the project](https://github.com/nasa-jpl/open-source-rover/projects/1) for context

**Comment by apollokit** [comment]
Inspiration: Eric's README updates: https://github.com/nasa-jpl/open-source-rover/pull/226#issuecomment-729933744

**Comment by dcschooley** [comment]
Here is a comment so that you can assign the conversion to me.

**Comment by dcschooley** [comment]
completed

**Comment by apollokit** [comment]
Is there a PR for this?

**Comment by dcschooley** [comment]
#245

I also have documentation updates in #243 and #248.
