### ISSUE TITLE
Port PCB Assembly doc to markdown

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#222]
The [doc](https://github.com/nasa-jpl/open-source-rover/blob/master/Electrical/PCB%20Assembly.pdf) to be ported

Refer to [the project](https://github.com/nasa-jpl/open-source-rover/projects/1) for context

**Comment by SConaway** [comment]
I'll take this one

**Comment by SConaway** [comment]
When there's only one step in any given heading, should it be numbered `1`?

**Comment by SConaway** [comment]
Are 16 or 17 100nF Capacitors needed? The TeX said 17, but I think it's 17 (R1-R17, inclusive)
