### ISSUE TITLE
Change Fuse Type

### ISSUE THREAD

**Issue by dcschooley** [nasa-jpl/open-source-rover#251]
The existing fuse on the circuit board does not give an indication if it is blown and replacing it requires desoldering the old one and soldering a new one in place. An improvement would be to replace the existing fuse with a 5x15mm or smaller glass fuse and a mount on the PCB. Another option would be to go with a larger glass fuse with a holder that can be panel mounted on the back panel for easy replacement. .

**Comment by Achllle** [comment]
yay, done because of Kit's great work!
