### ISSUE TITLE
Drive Motor Clamp - Mechanical over-constraint 

### ISSUE THREAD

**Issue by ericjunkins** [nasa-jpl/open-source-rover#26]
## Problem 
The attachment scheme for the drive motors leads to a mechanical over-constraint.

![motor_clamp_1](https://user-images.githubusercontent.com/25470708/44240318-5ccbbd80-a172-11e8-9c2c-59dc1edc694b.PNG)

Here we can see that the clamping force on the aluminum 25mm Diameter motor clamp will be over-constrained when bolting the clamp into the aluminum U-channel

![motor_clamp_2](https://user-images.githubusercontent.com/25470708/44240416-ce0b7080-a172-11e8-93e0-810eeaa44400.PNG)

The red arrows show the force put on the piece from the clamping screw, and green arrows show force put on by bolting to the u-channel. These force are in direct opposition, and overtime lead to one of two things:

 * The motor loosens inside the clamp and is allowed to free spin, which will tangle and eventually break your wires
 * The clamp loosens inside the u-channel and the wheel assembly becomes loose to the rest of the robot chassis

## Solution
The motor should mount on using the bolting pattern at the bottom of the motor, similar to the corner motor mounting scheme. This will alleviate this over constraint and allow all pieces to be tightened properly 

![motor_clamp_3](https://user-images.githubusercontent.com/25470708/44240531-820cfb80-a173-11e8-859c-39263c42d85b.PNG)

**Comment by siero89** [comment]
what about if instead using a clamping screw u use a magnetic clamp ?

**Comment by MisterUniverse** [comment]
Using a cotter pin at the end of the bolt will keep it from coming loose

**Comment by ericjunkins** [comment]
Will be updating documentation for the screw tightening order to properly take up mechanical tolerances
