### ISSUE TITLE
Update pcb assembly read me for rev F

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#263]
Had to rebase the changes from https://github.com/nasa-jpl/open-source-rover/pull/198 on top of master, and some stuff was out of date due to our shift to markdown documentation.

items to fix:

1. "updated documentation for J28" (see [here](https://github.com/apollokit/open-source-rover/commit/3c47b0a3e61809ce460036f0ee139cb108d75a36))

**Comment by Achllle** [comment]
Hopefully resolved :sweat_smile:
