### ISSUE TITLE
Add wheel drilling jig to the repo

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#270]
Prompted by this discussion https://github.com/nasa-jpl/open-source-rover/discussions/266

That shouldn't just be left floating around in dropbox somewhere...

**Comment by apollokit** [comment]
https://github.com/nasa-jpl/open-source-rover/discussions/266#discussioncomment-662406

**Comment by Achllle** [comment]
Referencing here as well, the file was uploaded to #46 and was referenced in [tex](https://github.com/nasa-jpl/open-source-rover/commit/eb802edeab4ba4f6ee0e4846acf702740f2b1007) but seemingly didn't make it when we transferred to markdown

**Comment by Achllle** [comment]
closing since no longer relevant with latest update
