### ISSUE TITLE
Add a table in OSR main repo that keeps track of HW/SW versions

### ISSUE THREAD

**Issue by apollokit** [nasa-jpl/open-source-rover#274]
The plan is to remove submodule links between the main osr repo (the HW) and the rover code repo (the Sw), keep them versioned separately, and do releases on both repos jointly.

We need a place to track these releases so it's always clear which SW version corresponds to which HW version.

1) Make this table in open-source-rover repo
2) Clean up any remaining versioned connections to the SW repo from the HW repo. There should be one source of truth.

**Comment by Achllle** [comment]
We've been doing this with the Releases feature!
