### ISSUE TITLE
Shaft Coupler - 

### ISSUE THREAD

**Issue by ericjunkins** [nasa-jpl/open-source-rover#28]
## Problem

There is sometimes slippage in the attachment between the shaft coupler and the motor shaft

![shaft_coupler](https://user-images.githubusercontent.com/25470708/44241114-bfbf5380-a176-11e8-8328-9247ca889fcf.PNG)

(this image shows socket head cap screws, which have been switched to button head screws for more clearance) 

Even with the de-coupling of the two clamping forces across the coupler it still sometimes does not grab onto the motor shaft well enough to hold the entire torque seen on the corners. 

## Solution

In order to keep the JPL open source rover up and running I've simply epoxied the couplers to the motor shafts, however for a hobby level project where one might want to change or reuse the motors this wouldn't be ideal. 

Instead a coupler that can appropriately grab onto the 4mm motor shaft would be idea. This could potentially include a redesign of the scheme of attaching the motor so that you can get increased length of motor shaft to attach to as well.

**Comment by davidadkins1** [comment]
Has anyone considered this? https://www.amazon.com/Stainless-Steel-Screw-Shaft-Coupler/dp/B00KQRRVHM

**Comment by vssystemluba** [comment]
@davidadkins1 we used shaft couplers that were extremely similar to those ones in our first design of the rover.  We found that no matter how hard we torqued down those set screws, they would always back themselves out and lose grip on the shafts.

**Comment by ericjunkins** [comment]
Initially we were using almost the exact part, however the torque seen on the corner system was higher than what the set screw was able to hold, and inevitably the set screws would loosen and back themselves out. Even with loctite this was the case eventually

**Comment by vssystemluba** [comment]
On a semi-related note, I know some roboticists use motors hex drive shafts.  Without doing much digging, I found these... http://www.revrobotics.com/rev-41-1301/.  If we found a way to mount a motor with a hex drive shaft, we might be able to solve the shaft coupler problem.

**Comment by ericjunkins** [comment]
I'm working on a potential 3D printed solution to this. I have designed and done a very quick test using an ABS based material, with good initial results.

**Proposed Solution**
![image](https://user-images.githubusercontent.com/25470708/45659346-d3791500-baa8-11e8-848c-9996f63f83ee.png)


**Motor Mounting Hub:**
![image](https://user-images.githubusercontent.com/25470708/45659362-e986d580-baa8-11e8-91ea-51e20d294d02.png)

Mounts the motor slightly higher up, but gives a more convenient access to the two screws that bolt into the motor. Instead of having to disassemble the entire coupler-standoff system to get to them the whole motor mount just uses the 4 bolting holes used for the pillow bearing standoffs as well. 

**Shaft Coupler:**
![image](https://user-images.githubusercontent.com/25470708/45659403-2226af00-baa9-11e8-8cec-2d6257da8c04.png)

This coupler takes advantage of the D-profile on both of the shafts, which will be the mating face for torque transmission. In addition with the decrease in outside diameter the upper half of the coupler can be extended to the entire length of the 4mm motor shaft, giving increased contact area. Set screws with heat set inserts will be added to handle axial loads only.

I'm going to test with ABS first and then afterwards test with Poly-Carbonate ABS well for increased hardness on the coupler.

**Comment by vssystemluba** [comment]
Based on this discussion, the discussion and eventual solution on the OSR forum at https://www.tapatalk.com/groups/jpl_opensource_rover/shaft-coupler-solutions-discussion-t69.html, and @kevincloutier's pushed solution (9b407a6), I am closing this issue as solved.  Thanks everyone for the input and the design improvement!
