### ISSUE TITLE
Create a list of builders with pictures of their rover

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/open-source-rover#280]
I think it would be fun // lower the barrier to contribution if we had a readme with a table containing images and short descriptions of some of the builders' OSRs. People would submit a PR to have their rover featured on the page.

**Comment by ericjunkins** [comment]
That seems like a great idea!

**Comment by apollokit** [comment]
Agreed. [Reposting in the slack](https://opensourcerover.slack.com/archives/C01CTNRDERJ/p1621829007025700)

**Comment by Achllle** [comment]
#322
