### ISSUE TITLE
Consistent case for Readme filenames

### ISSUE THREAD

**Issue by sethfischer** [nasa-jpl/open-source-rover#281]
All but the following Readme files are named `README.md` (having a lowercase extension):

* `optional_cad_parts/README.MD`
* `parts_list/README.MD`

# Solution

Rename the above two files to `README.md`.

**Comment by seudonym** [comment]
Hi, can I help contribute to the project.

**Comment by solmazi** [comment]
بله ممنون میشوم

**Comment by aktfire747** [comment]
Can we have that in english, or is there  way to translate in github?

**Comment by apollokit** [comment]
^ lol, I won't be helpful on translating there
