### ISSUE TITLE
Errors in parts list

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/open-source-rover#300]
from Slack:

> E46 is twice in the master parts list and i think the second one (yellowjacket 223rpm deive motor) is supposed to be the E49. Is this right?
Next Question is, that i see 3 types of motors:
The yellowjacket, the gear motor (corner motor)(E46) and the Gear motor (drive motor)(E45).

What should happen:
* `YellowJacket 223 rpm drive motor` should be `E49`, not `E46`
* the line with `E45` should be removed

**Comment by rbrishabh** [comment]
I can help with this!
