### ISSUE TITLE
Consider referencing https://opensourcerover.jpl.nasa.gov from the repo description

### ISSUE THREAD

**Issue by dmittman** [nasa-jpl/open-source-rover#32]
Just like you can edit the repo's description, you can also designate a website that is related to the repo. I suggest that https://opensourcerover.jpl.nasa.gov would be an appropriate website.

If a committer gives this issue an up-vote, I'll implement.

**Comment by vssystemluba** [comment]
Just implemented myself since it's quick and easy.  Thanks for mentioning the website in the description; it's a good idea to link it there.
