### ISSUE TITLE
Figure style

### ISSUE THREAD

**Issue by sethfischer** [nasa-jpl/open-source-rover#329]
Figures are displayed in two styles.

1. Image followed by an emphasized caption:

```markdown
![](../images/calibration/is6.png)
**Figure 6**
```

2. Figure and caption within a table:

```markdown
| <img src="../../images/pcb_assembly/assembly/standoff_5.png" width="300"> |
|:-:|
| Figure 15: Raspberry Pi Standoffs |
```

Standardizing on a single style would improve the consistency of the documentation.

**Comment by sethfischer** [comment]
Which is the preferred image style?

**Comment by ericjunkins** [comment]
The html version is preferred because it allows you to control properties like width and positioning

**Comment by Achllle** [comment]
We want to use as much vanilla markdown as possible, but have been deviating in cases where finer control of the figures is necessary, for example when we're placing two large figures next to one another. My personal take is that it's OK to have both. Requiring HTML everywhere would make the contribution threshold even higher and if the basic markdown works, it works :)
