### ISSUE TITLE
Offer FreeCAD fcstd files as an alternative to Solidworks 

### ISSUE THREAD

**Issue by luzpaz** [nasa-jpl/open-source-rover#33]

**Comment by ericjunkins** [comment]
There are step files and igs files provided as alternatives to Solid works parts

**Comment by luzpaz** [comment]
If someone took the time to convert said step and igs files to FCstd files, would you consider including them in this repo ?

**Comment by ericjunkins** [comment]
I'm unfimiliar with that file type. What benefit does that type have beyond igs and step files? By file size the CAD already takes up a huge amount of space so it's prefer not to just keep adding CAD file types unless there's a compelling argument

**Comment by vssystemluba** [comment]
Agreed.  FCStd is basically a .zip file that includes a STEP file plus a lot of other things that we don't really need or use for this project, so I'm hesitant to include those files in the repository.  FreeCAD can import STEP files natively, so if anyone does need an FCStd file, FreeCAD would be an easy way to create one from the contents of this repository.
