### ISSUE TITLE
Remove `Monolithic Board.*` files

### ISSUE THREAD

**Issue by sethfischer** [nasa-jpl/open-source-rover#338]
`Monolithic Board.*` files are not relevant to the current version of the rover.

1. Remove `Monolithic Board.*` files:

    * `electrical/pcb/control_board/Monolithic Board-rescue.bck`
    * `electrical/pcb/control_board/Monolithic Board-rescue.dcm`
    * `electrical/pcb/control_board/Monolithic Board.bak`
    * `electrical/pcb/control_board/Monolithic Board.kicad_pcb-bak`
    * `electrical/pcb/control_board/Monolithic Board.pro`
    * `electrical/pcb/control_board/schematics/Monolithic Board.pdf`
    * `electrical/pcb/control_board/schematics/Monolithic Board.plt`

2. Update `electrical/README.md`:

    > moving towards a monolithic "motherboard" approach

    As this is now the current approach.

### Notes

There are also `Monolithic Board.*` files in:

* `electrical/pcb/control_board/gerbers/rev_d/`, and
* `electrical/pcb/control_board/gerbers/rev_e/`.

If `Monolithic Board.*` files were intended to be part of revision D and revision E then these directories should remain unchanged.

**Comment by apollokit** [comment]
Already removed as part of https://github.com/nasa-jpl/open-source-rover/pull/198 :)
