### ISSUE TITLE
4-pin headers 0.1 not 0.05"

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#34]
The specs call for common 0.1" headers on the PCBs.  The master parts list, however, has a Digi-Key link to **0.05"** headers.  (as well as 40 pin 0.1" headers which I see no reference to x- perhaps to break into 4 pin units?)  I searched the docs and found no reference to 0.05" anything.  Error?  If so, will need to swap out with Digi-Key.

**Comment by ericjunkins** [comment]
There should only be 0.1 inch standard pin headers and connectors. I'll check through for the digikey parts and fix error if necessary
