### ISSUE TITLE
Use relative paths for images

### ISSUE THREAD

**Issue by sethfischer** [nasa-jpl/open-source-rover#340]
## Proposal

Make all image src links relative.

## Justification

Using relative links allows correct rendering of a local preview. For this reason [GitHub's docs recommend using relative links](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links):

> Relative links are easier for users who clone your repository. Absolute links may not work in clones of your repository - we recommend using relative links to refer to other files within your repository.

Being able to preview rendered Markdown before pushing is important as it can reduce the number of errors.

## Example

In `mechanical/head_assembly/README.md` there is one relative link, with the remaining being absolute.

The image with the relative link displays in a local preview with the remaining absolute images being broken.

### Relative link

```markdown
| <img src="../../images/components/structural/S43.png" width="50%"> |
| :--: |
| Figure 1: 3D Printed Parts |
```
![relative-image-link](https://user-images.githubusercontent.com/2492233/126023027-d246bc64-202f-4e1a-82ce-06dea545307a.png)

### Absolute link

```markdown
<img src="/images/head/finala.png" width="50%">
```
![absolute-image-link](https://user-images.githubusercontent.com/2492233/126023032-951a215f-9fae-4789-97fa-41c54da1045b.png)

**Comment by sethfischer** [comment]
If this proposal is accepted I will prepare a pull request.

**Comment by ericjunkins** [comment]
Sounds good assigned it to you
