### ISSUE TITLE
Reference CAD location in Parts List for 3d printed parts

### ISSUE THREAD

**Issue by JoshSharpe** [nasa-jpl/open-source-rover#349]
Problem: Right now, when looking at the CAD parts that are in various places in the repo, it can be difficult to understand if the part is needed, why it would be, and which part it is on the master parts list. 

This can be solved a few different ways.

- In the parts list, include the directory and file name for the STL file that it refers to
- Include the reference number (ie S24) of the part in the stl file name
- Create a README file for the CAD parts that includes reference number, description of part, location, etc.

**Comment by Achllle** [comment]
As a meta-comment, we are considering moving from SolidWorks to OnShape. If you have ideas on how to achieve this with OnShape, if it still could be an issue, I'd love to hear it!

**Comment by Achllle** [comment]
closing since no longer relevant with latest update
