### ISSUE TITLE
Corner wheel hard stop standoff length

### ISSUE THREAD

**Issue by vssystemluba** [nasa-jpl/open-source-rover#35]
(This issue was created from a post on the forum at: http://s15.zetaboards.com/JPL_OpenSource_Rover/topic/10561104/1/ )

Table 4 in section 2.2 of the wheel assembly instructions lists T3 as #6-32x3/8" threaded standoffs. The only T3 I can find in the parts lists is .75" in length. Should it be 3/8" or 3/4"? 

Also, what is the 5/16" wrench, also in table 4, used for?

Thanks!

**Comment by ericjunkins** [comment]
Also the 5/16" Wrench was a tool just put in every one of the tools tables along with the allen key set as they were needed in almost every step. It appears this assembly doesn't have any hex nuts involved so doesn't need the 5/16" wrench
