### ISSUE TITLE
Wheel assembly picture update required

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/open-source-rover#357]
See also #356 
Figure 4 needs its own picture
Figure 5b shows the wrong screws (it uses the S48 srews). Instead B1 should be used which aren't visible.

**Comment by Achllle** [comment]
You're most welcome to create pull requests to make edits! 
We are however in the process of getting everything ready for V2 of the OSR which would supersede these issues. A lot of help is needed to complete documentation there. If you're interested, I recommend joining the slack group (link on main readme page) and posting in the #osr-upgrade channel

**Comment by l2eza** [comment]
@Achllle Ah perfect! thank you! 🐈‍⬛

**Comment by Achllle** [comment]
closing since no longer relevant with latest update
