### ISSUE TITLE
Rocker-Bogie Assembly spacing issue

### ISSUE THREAD

**Issue by xtream1101** [nasa-jpl/open-source-rover#36]
In Section 2, Step 2 of the Rocker-Bogie Assembly, when using the T1 (1/4") spacer it creates to much of a gap it seems, also need to use B4 (5/8") screws to connect it. I would think that the size of the spacer is incorrect and should be a smaller size. Is this correct?

[Photo of the spacing with 1/4" spacer](https://photos.app.goo.gl/Rk7QB4n5XqdCiLCX9)

**Comment by ericjunkins** [comment]
The 1/4" spacer is the correct length of spacer for the distance, but the 5/8" should be the screw used, it says 3/4" right now. 

![image](https://user-images.githubusercontent.com/25470708/45329358-e4f47700-b514-11e8-8c67-86196d67b662.png)

![image](https://user-images.githubusercontent.com/25470708/45329366-f3db2980-b514-11e8-9fef-726ae4900488.png)

**Comment by ericjunkins** [comment]
Just following up on this, did you end up still seeing an issue here? Figuring out if this needs to be looked into further

**Comment by xtream1101** [comment]
It seemed to fit together fine. Things started to line up better after the whole thing was assembled.
