### ISSUE TITLE
[Bug Report] S50 (3D Printed PVC Clamping Hub (bottom)) is not recorded in the master_parts_list_raw.csv

### ISSUE THREAD

**Issue by SallyTYT** [nasa-jpl/open-source-rover#376]
https://github.com/nasa-jpl/open-source-rover/blob/master/parts_list/master_parts_list_raw.csv

https://github.com/nasa-jpl/open-source-rover/blob/master/mechanical/body_assembly/3d_printed_parts/pvc_hub_lower.stl

**Comment by Achllle** [comment]
closing since no longer relevant with latest update
