### ISSUE TITLE
[Bug Report] There is a problem with the location of the holes in the drawing for S35 (top_plate_baseline.dxf)

### ISSUE THREAD

**Issue by SallyTYT** [nasa-jpl/open-source-rover#377]
There is a problem with the location of the drawing holes, resulting that the Control Board can not be installed.

https://github.com/nasa-jpl/open-source-rover/blob/master/mechanical/body_assembly/laser_cut_parts/top_plate_baseline.dxf

![image](https://user-images.githubusercontent.com/64485819/179875506-fb32893e-3438-4f9e-ab31-e9993e90fe81.png)

**Comment by Achllle** [comment]
closing since no longer relevant with latest update
