### ISSUE TITLE
Inconsistency in 'Electrical Parts List.xlsx'

### ISSUE THREAD

**Issue by FalseIsNotTrue** [nasa-jpl/open-source-rover#4]
- Resistors 10K (row 11):
Expected Resistor based on the name: 10 kOhms
Resistor refered to in the Link column: 21 kOhms ([digikey.com product page](https://www.digikey.com/product-detail/en/vishay-bc-components/MRS25000C2102FRP00/PPC21.0KZCT-ND/594966))
Resistor found based on Model/Config column: 'CF14JT200KCT-ND' 200kOhms ([digikey.com search](https://www.digikey.com/products/en?keywords=CF14JT200KCT-ND))

- Resistors 22K (row 12):
Expected Resistor based on the name: 22 kOhms
Resistor refered to in the Link column: 20 kOhms ([digikey.com product page](https://www.digikey.com/product-detail/en/stackpole-electronics-inc/CF18JT20K0/CF18JT20K0CT-ND/2022773))
Resistor found based on Model/Config column: '301KXBK-ND' 301 kOhms ([digikey.com search](https://www.digikey.com/products/en?keywords=301KXBK-ND))

**Comment by ericjunkins** [comment]
Thanks for catching this, values updated in the electrical parts list
