### ISSUE TITLE
B13 links to wrong size screw

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#40]
B12 #2-56 x 3/16" Button head screw has a link to McMaster 1/4" screw.  Don't think it makes any difference, but....

**Comment by accidentalmeme** [comment]
The "# 2" links to issue 2.

**Comment by JHPHELAN** [comment]
I believe the #2 refers to the screw size: #2-56.  
My concern is that the screw length is listed as 3/16" but the source link refers to a 1/4" screw.
Will have a better sense of which is right as we get into the build.

Jim Phelan, Mars Rover project lead, **Houston Robotics**

**Comment by vssystemluba** [comment]
Resolved by e243445
