### ISSUE TITLE
Custom PCB instructions missing

### ISSUE THREAD

**Issue by karbak** [nasa-jpl/open-source-rover#415]
I'm not sure if I'm not looking for the right terms, but the instructions for ordering/fabricating the custom PCB/s seem to be missing. I can't find it on the parts list, or in the main README. I do see some relevant files in the electrical/pcb folder, but can't find any instructions on how to use them. The PCB assembly instructions seem to start by assuming one already has the PCB available.  Pointers appreciated if I've just missed some part of the documentation.

**Comment by Achllle** [comment]
You're right, with the latest merge they got deleted instead of moved by accident. You can find instructions [here](https://github.com/nasa-jpl/open-source-rover/tree/d25869b4e94407a4e3408112f096a2f84e93b0ae/electrical). I'll add them back in.
