### ISSUE TITLE
Miscount of 1106 square beams

### ISSUE THREAD

**Issue by abust005** [nasa-jpl/open-source-rover#421]
Currently building the rover, according to the BOM, there should be 5x 1106 (29-hole, 232mm) and 6x 1106 (41-hole, 328mm), but the OnShape shows 7x 1106 (29-hole) and 4x 1106 (41-hole)

**Comment by Achllle** [comment]
I will address this, thanks for reporting. The OnShape model doesn't show two 29-hole beams that are for structural support but can be considered optional. You only need 4x 41-hole beams.
