### ISSUE TITLE
404 for 2D DFX files on both master and branch

### ISSUE THREAD

**Issue by sk19810** [nasa-jpl/open-source-rover#422]
URL is giving 404 ... https://github.com/nasa-jpl/open-source-rover/tree/master/mechanical/body/dxf

**Comment by Achllle** [comment]
Link that needs to be updated is [here](https://github.com/nasa-jpl/open-source-rover/blob/43ef9565b3addaa4a571b478ff1ce8192add58ba/README.md?plain=1#L138)

**Comment by Achllle** [comment]
solved with #423
