### ISSUE TITLE
Electronics Board: shortest RoboClaw needs 8 x #4 washers to make tight

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#43]
The 5th RoboClaw motor controller on the Electronic board is supported by #4-40 1/4" stand-offs and 4-40 1/4" screws.  1/4" stand-off shared by 2 screws = 1/8" each.  The Electronics Board is 1/8" acrylic allowing its screw to extend 1/8".  The RoboClaw board is only 1/16" leaving a gap of 1/16" play when its screw meets its partner in the stand-off.  A couple #4 washers does the trick and there's plenty left over.  The purpose of the staggered elevation of the stand-offs is supposedly to allow room to access the USB port on the RoboClaw for testing and calibration.  Seems this could have been accomplished as easily by rotation or translation of the RoboClaw but we won't know til wiring time what the reality of that situation is.
Jim Phelan, Mars Rover project lead, **Houston Robotics**

**Comment by ericjunkins** [comment]
I"ll look into these comments on screw lengths and standoff lengths. It is true rotation could have been done to have access to micro USB ports, I chose to keep the wire routing for the Power to the motor controllers as simple as possible. I certainly would be open to suggestions as to other possible configurations of electronics boards that could make things easier! :)

**Comment by vssystemluba** [comment]
Closing this issue as there are workarounds mentioned above.  @JHPHELAN if you feel strongly that this should be referenced in the master build documents, please submit a pull request and we'll get it merged.
