### ISSUE TITLE
3D Model Files for Parts

### ISSUE THREAD

**Issue by RobotLAB123** [nasa-jpl/open-source-rover#440]
Does anyone have the STL or SLDPRT files for parts: S24, S31 and S43? I am trying to print these and can only find the PNG files.

**Comment by RobotLAB123** [comment]
Or are all of the 3D parts (except for S41) no longer necessary?

**Comment by ericjunkins** [comment]
Sorry, can you clarify what version of the robot you're working on? The mechanical reference designators I believe only really applied to the initial build of the rover which can be found in the [releases](https://github.com/nasa-jpl/open-source-rover/releases) where you can find all the old files. I believe 3D printed pieces are no longer used in our most up to date version of the rover

**Comment by Achllle** [comment]
@RobotLAB123 You need to check out version 3.0.0 from the releases list @ericjunkins mentioned. You can check out a particular version by clicking on the link to it or on the main github page, selecting the button that says 'master', then select 'tags' and 'v3.0.0'.
That way you'll find the files for that older build version, which includes for example S31 [here](https://github.com/nasa-jpl/open-source-rover/tree/v3.0.0/mechanical/corner_steering/3d_printed_parts). Let me know if that solves your question.

**Comment by RobotLAB123** [comment]
That does answer my question. Thank you guys for the help!
