### ISSUE TITLE
PCB build instructions use part references that are only documented on google sheets

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/open-source-rover#443]
Instructions in [pcb build](https://github.com/nasa-jpl/open-source-rover/tree/master/electrical/pcb#33-solder-resistor-r1-and-power-diode-d1) reference things like 'diode D1' and 'resistor R1' but those are nowhere to be found in the repo. They should be specified.

In the meantime, the part references are [here](https://docs.google.com/spreadsheets/d/1Z011-4hdfSKOZROEwKTmGs-w_xfm9FzWOGzqSnaTu4w/edit?usp=sharing). 

Either remove references like D1 and just specify the resistor value + code or specify which is which somewhere.

**Comment by apollokit** [comment]
🙈 yeah definitely need to do this

**Comment by apollokit** [comment]
Opened a PR here https://github.com/nasa-jpl/open-source-rover/pull/448

**Comment by apollokit** [comment]
Done.
