### ISSUE TITLE
Typo in the parts_list.csv file

### ISSUE THREAD

**Issue by UTNAK** [nasa-jpl/open-source-rover#445]
I found a typo in the parts_list.csv file, lines 54-59.
The short name might be modified to match the correct long name.

<img width="715" alt="typo_on_partlist" src="https://github.com/nasa-jpl/open-source-rover/assets/29029659/41aa144a-482f-41f0-8be0-5767c36964b5">

**Comment by Achllle** [comment]
This has been resolved a while back
