### ISSUE TITLE
Discrepancy in Roboclaw setup vs configuration in config

### ISSUE THREAD

**Issue by ericjunkins** [nasa-jpl/open-source-rover#447]
The instructions and wiring say that the following should be how it is setup/built:

**RC1**

Address : 128
M1: Front Left
M2: Middle Left

**RC2**

Address: 129
M1: Back Right
M2: Back Left

Address: 130
M1:  Front Right
M2: Middle Right

However that is not what the params file says in the code. 

https://github.com/nasa-jpl/osr-rover-code/blob/master/ROS/osr_bringup/config/roboclaw_params.yaml. 

![image](https://github.com/nasa-jpl/open-source-rover/assets/25470708/15f290db-4d74-4d20-bb52-dd6f2729fbd6)

**Comment by Achllle** [comment]
Can you link to the parts of the instructions and wiring that you're referring to specifically? The [wiring README](https://github.com/nasa-jpl/open-source-rover/blob/master/electrical/wiring/README.md) doesn't deal with roboclaws, it's just instructions for how to make the wires themselves.

**Comment by ericjunkins** [comment]
![image](https://github.com/nasa-jpl/open-source-rover/assets/25470708/ec6668ee-e2fc-428d-9c54-b23f7b045b11)
 I was going with what's on the board, which I have verified is correctly connected to where it says it is on the PCB

**Comment by Achllle** [comment]
Woops, looks like I've been pluggin in my cables for the front right motor in the back right and vice versa. Even though I labeled them correctly :1st_place_medal:
Just to verify: the fix you're expecting is to make is to just flip the addresses of `drive_right_back` and `drive_right_front` in `roboclaw_params.yaml`?

**Comment by ericjunkins** [comment]
Yes that is my plan to just fix the config to match the PCB
