### ISSUE TITLE
Helpful jig for drilling clamping hub mounting holes in Traxx wheels

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#46]
When the **Houston Robotics** Mars Rover team began to address the drilling of the mounting holes in the Traxx wheels, we pondered how we might more accurately accomplish this.  Initially we considered a vertical lathed spindle 12mm at the bottom to fit the wheel and 4mm at the top to fit the hub.  Rotational orientation would still be by hand and there was concern that using the hub itself as a guide may damage the threads.  We consulted the Houston Community College Stafford manufacturing campus Fab Lab supervisor **Roland Fields**.  He suggested a more modern high tech approach of creating a 3D printed jig to fit the wheel hub to include appropriately spaced holes to guide pilot hole drilling.  He directed us to lab assistant **Frederic Lemme** who whipped up a prototype on SolidWorks.  After tweaking for fit, a further modification adding a hex nut shape to fit into the wheel ensured fixed alignment of the pilot hole guides to the target area.  **Houston Robotics'** **Omar Gomez** and son accomplished the final drilling.  The screws to attach the wheel to the hub seemed excessively long, but that's an issue for further along the build.  ATTACHED is a drawing of the wheel adapter and zip file of the .SLDPRT and .STL files.  Copyright 2018 **Houston Robotics**, free to use with acknowledgement.
![wheel adapter v1](https://user-images.githubusercontent.com/35434147/46052190-defcb980-c102-11e8-8354-38d64aa43667.png)

Jim Phelan, Mars Rover project lead, **Houston Robotics**
[wheel_adapter3.zip](https://github.com/nasa-jpl/open-source-rover/files/2425541/wheel_adapter3.zip)

**Comment by ericjunkins** [comment]
I have added a note in the Wheel assembly build document to link to this issue so others can access and try using your jig! Thanks for the addition, I hope it is helpful for others.

**Comment by JHPHELAN** [comment]
Glad we could be of help.  Would love to see what other groups made to solve the same issue.  Consistency of supplies/suppliers is always an issue.  The last remaining par to acquire, one of the pillow blocks, is _still_ on backorder!  Fortunately in skilled 3D CAD hands (not mine!) a custom jig was designed in less than an hour and simplified the job greatly.

**Comment by philwil** [comment]
Used the Wheel adapter yesterday. It worked really well.
I am thinking of using one on each wheel to support the hub better.
Looking at the alignment the wheels could use a 1/4 spacer to put the center of the wheel under the pivot point.
I am also going to try to add grub screws to the hubs to get a better lock on the motor drive shaft.
  
Any thoughts on using 4 holes to mount the wheels as well.

**Comment by JHPHELAN** [comment]
"Any thoughts on using 4 holes to mount the wheels as well."
According to other builders that are more mechanical engineering minded than I:
Since the two sides of the hub clamp have to move toward each other to grip the shaft, fixing it in place with 4 screws would inhibit that making it "overconstrained."
Jim Phelan
Mars rover project lead, Houston Robotics

**Comment by kevincloutier** [comment]
@JHPHELAN I printed this last evening, it fits perfectly. Thanks!

**NOTE:** When I opened the STL in Repetier-Host, the scale was way off (both Mac and Windows). So, I imported the SolidWorks file into Fusion 360, and exported the STL again, and that worked.... just a note for anyone running into similar issues.

**Comment by philwil** [comment]
I just sent the STL file off to makexyz and it returned a perfect fit.
All wheels are mounted now !! working on the rocker boogie next..

**Comment by kevincloutier** [comment]
My "educated guess" is I don't know what I am doing.... but importing and exporting worked for me!!!!

**Comment by philwil** [comment]
I also used a small set screw drilled through the hub to help with the
clamping.
The hub still clamps but I did not make the extra cuts in it.
If the wheels fall off I'll add a small indent in the shaft to lock the set
screw.
I only have a dremel and a bench stand at the moment so mechanics are rough.

**Comment by kevincloutier** [comment]
@philwil Could you elaborate? I understand you didn't make the cut, but did you drill through S14 to insert a set screw? I think I am misunderstanding what you wrote...

**Comment by philwil** [comment]
Yes I did exactly that.
Used a 3mm setscrew.
Did the same things on the steering hubs too.
I also am working on a much cheaper absolute position sensor.

**Comment by kevincloutier** [comment]
Wow, for a guy with a "dremel", that's impressive! I have a drill press and I don't think I would try that without first seeing you do it! Nice work!
