### ISSUE TITLE
goBilda 1514-0010-0060 spacer discontinued

### ISSUE THREAD

**Issue by robrussell** [nasa-jpl/open-source-rover#469]
The [1514 Series 8mm ID Spacer (10mm OD, 6mm Length)](https://www.gobilda.com/1514-series-8mm-id-spacer-10mm-od-6mm-length-4-pack/) (`1514-0010-0060`) from goBilda required in the [Parts for rocker bogie assembly](https://github.com/nasa-jpl/open-source-rover/blob/master/parts_list/README.md/#parts-for-rocker-bogie-assembly) section is discontinued.

1514-0010-0060 is used in the [Creating the rocker-bogie joint](https://github.com/nasa-jpl/open-source-rover/blob/master/mechanical/rocker_bogie/README.md) section of the instructions.

**Comment by Achllle** [comment]
Looks like the exact same part to me, can't believe they 'replaced' it just to charge more...
