### ISSUE TITLE
Update docs to use new bearing

### ISSUE THREAD

**Issue by abust005** [nasa-jpl/open-source-rover#480]
Bearing used in rocker-bogie ( [1601-0014-0008](https://www.gobilda.com/1601-series-flanged-ball-bearing-8mm-id-x-14mm-od-4mm-thickness-2-pack/) )has been discontinued and replaced with [1611-0514-0008](https://www.gobilda.com/1611-series-flanged-ball-bearing-8mm-id-x-14mm-od-5mm-thickness-2-pack/).

This may require testing and validation, as the replacement is 1mm thicker.

**Comment by Achllle** [comment]
Tried replacing within OnShape. The spacers are a fraction of a mm too thick now, but I believe that won't cause much of an issue. Will submit a PR for the change, let me know if you think this will create issues.
![image](https://github.com/nasa-jpl/open-source-rover/assets/14060847/de65a651-9f55-49d8-8be9-2cf79ac1ff7d)

**Comment by abust005** [comment]
Looks good to me, if anything you might be right with what you said in the Slack, this could actually be positive.

**Comment by Achllle** [comment]
I just noticed that the [parts list](https://github.com/nasa-jpl/open-source-rover/tree/master/parts_list#parts-for-rocker-bogie-assembly) is already pointing to the newer version. It seems like only the OnShape model was outdated.
