### ISSUE TITLE
Are urdf files available for the rover? Gazebo simulation?

### ISSUE THREAD

**Issue by Mechazo11** [nasa-jpl/open-source-rover#481]
Hi,

I was wondering if the URDF files are available for this rover or has it been simulated in Gazebo before?

With best,
@Mechazo11

**Comment by Achllle** [comment]
yes, the URDF and Gazebo simulation files are in the code repository, [here](https://github.com/nasa-jpl/osr-rover-code/tree/master/ROS/osr_gazebo)
