### ISSUE TITLE
Github Enhancement Proposal

### ISSUE THREAD

**Issue by debpedrano** [nasa-jpl/open-source-rover#49]
Hello Project Owner, can I make a logo design for this project? I am a open source contributor and I am willing to work with you.

**Comment by ericjunkins** [comment]
Hi, we'd love to hear some of your ideas! I think over email is a better way, feel free to send me a message at eric.junkins@jpl.nasa.gov

**Comment by debpedrano** [comment]
okay, thank you for your response. I will message on your email after making a design.

**Comment by debpedrano** [comment]
@ericjunkins 

how about this one?
![image](https://user-images.githubusercontent.com/40510200/46268037-d7a63780-c56a-11e8-9c24-aefa759a5e3a.png)

**Comment by debpedrano** [comment]
![image](https://user-images.githubusercontent.com/40510200/46268209-c1e54200-c56b-11e8-8ee2-2e2042d1f04f.png)

**Comment by spockbuddha** [comment]
MAKE IT DYNAMIC  PLEASE

**Comment by debpedrano** [comment]
@spockbuddha , what do you mean by dynamic? I am sorry, I am not professional so I need your further perspective or explanation about your desired design. Thank you

**Comment by debpedrano** [comment]
Hello, can I update the issue? please response. Thank you :)

**Comment by debpedrano** [comment]
@ericjunkins  Thank you :)

**Comment by vssystemluba** [comment]
Closing this issue in favor of the more active discussion on the OSR forum at https://www.tapatalk.com/groups/jpl_opensource_rover/mission-logo-for-the-open-source-rover-t104.html.
