### ISSUE TITLE
Android Studio Image is incorrect in documentation

### ISSUE THREAD

**Issue by MyqlGodfrey** [nasa-jpl/open-source-rover#56]
The documentation that describes how to download/compile Android app is incorrect.
It shows the wrong line number in the image, but shows the correct string.
This is confusing.

**Comment by vssystemluba** [comment]
Can you provide more details?  which document, which page, and which image is incorrect?

What should it read?

**Comment by vssystemluba** [comment]
I added some clarity in that document in commit e07f710 which should address your issue.  Let me know if anybody still finds it unclear.
