### ISSUE TITLE
Logic Shifter output pins scrambled vs LED display input pins

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#59]
Logic Shifter output pins scrambled vs LED display input pins

![img_4073](https://user-images.githubusercontent.com/35434147/47971296-a16e4300-e055-11e8-9c64-9d3e77303c03.png)
![img_4084](https://user-images.githubusercontent.com/35434147/47971297-a16e4300-e055-11e8-9a3c-df624c516035.png)

In Fig 31 "Raspberry Pi connections to LED matrix", the LED MATRIX input pins are in the same configuration as the 8x2=16 pin IDC connector jack on the LED display.  However, on the Logic Shifter Board the output pins in P5, P6, P7 & P8 have no relation to the LED display input pins creating a chaotic "spaghetti farm" of jumper wires.  P8 has one ground pin and one unconnected pin.  There are 4 ground pins on the LED display.  Adafruit recommends grounding all of them (although they are connected internally in the LED display).  P8 could easily have made a place for all 4 of them.  

Even better, however, would have been to replace P5-P8 with an 8x2 header on the lower edge of the Logic Shifter Board (or moved the board closer to the LED input in the head) so that the provided ribbon cable (or home made if not provided with LED display) could be plugged directly into the Logic Shifter Board with the Logic Shifter ouput / LED display input routed logically to the connector.

A similar 16 pin connector could also replace P1-P4 connecting between the Logic Shifter Board input and the Raspberry Pi (although the 1/2" neck hole in the body would have to be enlarged) and sort out the connections on the Raspberry Pi end.  Better still, put the Logic Shifter on a GPIO break-out "hat" on the Raspberry Pi and just send a single 16 conductor ribbon cable directly to the LED Display input in the head (plus the power cable).  The break-out board should also include a 4-pin connector to connect to the Serial Splitter Board.

James Phelan
Mars rover project lead
**Houston Robotics**

**Comment by vssystemluba** [comment]
Closing as this is no longer relevant after the merging of the electronics-pcb-rework branch 1245e914998c893c12e6b350123e3883899f1534
