### ISSUE TITLE
Use The International System of Units in documentation

### ISSUE THREAD

**Issue by little-arhat** [nasa-jpl/open-source-rover#6]
To inspire future scientist and engineers it would be nice to convert imperial units in documenation to SI.

**Comment by ericjunkins** [comment]
I've added an "SI Units" attribute table for the specifications. However for most of the build documentation in most cases I believe it makes sense to remain on imperial system. The parts are made and designed as imperial parts/dimensions, and use imperial tools. If there are specific examples which you think make sense to convert to SI however feel free to point those out

**Comment by little-arhat** [comment]
@ericjunkins Thanks!
