### ISSUE TITLE
Files from Layout Software

### ISSUE THREAD

**Issue by weigu1** [nasa-jpl/open-source-rover#60]
Hi,
We are building the robot in our school (Luxembourg). As we are etching the PCBs our-self, we would need the layout. Is it possible to add the files from the Layout software (eagle, sprint layout ...) to the repo?

Greetings Guy

**Comment by ericjunkins** [comment]
Hi @weigu1,

The board layouts were done in Atlium, which I believe doesn't particularly play nicely with other softwares for PCB designing. I will look into some potential solutions for this, the best thing might be to just recreate the layouts in something like KiCAD so everyone can access and edit them.

**Comment by weigu1** [comment]
Thanks :)
