### ISSUE TITLE
Kill Switch

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#63]
Kill Switch:
It is my firm belief that, just as NASA has a Range Safety Officer whose job it is to abort a mission should the missile veer off course, every test of a robot of more than trivial power needs a Robot Safety Officer whose job it is to stop the robot should it behave in unintended ways.  To this effect we installed a "kill switch", a keychain remote controlled power switch.  We placed it between the voltmeter and the RoboClaw power tree while allowing unimpeded power take-off to the 5V regulator and thus to the brains of the robot.  In addition to the main power switch, the RSO must activate the remote to permit power to the motors.  Another push of the remote button stops the rover in its tracks.  The one pictured was obtained long ago from a forgotten source.  A Google of "keychain remote" will reveal many similar.  The photo also reveals two other modifications made to the laser-cut acrylic back plate.  One was for the power switch which was awkward to place elsewhere on the body.  Two additional holes permitted passage of the battery connectors which don't fit the 1/2" holes in the aluminum pattern plates.  Future modification plans are to replace the power toggle switch with an illuminated button switch, the better to indicate the power status & facilitate emergency shut-off.
James H Phelan
Mars rover project lead
**Houston Robotics**
![kill switch b](https://user-images.githubusercontent.com/35434147/48306979-e2100580-e508-11e8-9477-13b69386e4f8.jpg)

**Comment by vssystemluba** [comment]
Great addition to the rover!  For safety, I highly recommend building something like this into your robot for remote cutoff.

However, for price, we stuck with the hard power switch.  I'll therefore close this issue, but thanks for writing up your addition!  Feel free to write up some instructions and a basic parts list and add those to the repository as a pull request!
