### ISSUE TITLE
Missing CAD Parts

### ISSUE THREAD

**Issue by StoesserLukas** [nasa-jpl/open-source-rover#65]
Hey guys,

I´m trying to put the Robot and its CAD-Parts into Windchill, a Software to manage the whole Build. When I try to open the "Corner Steering Assembly.SLDASM" on SolidWorks, I always get an error, which says the "corner cap.SLDPRT" and "Corner Cap base.SLDPRT" files can´t be found. Unfortunately I`m not able to find These files here on GITHub. Does somebody know, where they are ? :-)

**Comment by vssystemluba** [comment]
Closing this as the same issue is also documented in #72.
