### ISSUE TITLE
add MotorCap.stl file to 3D printed folder in Corner Steering

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#72]
Protection for corner steering motors.
The rock climbing picture shows them.  There is discussion in the Open Forum about posting the 3D print file, but I can't find it.  

We discovered the need for corner motor protection when inverting the rover into "dead cockroach" position to work on the electronics board.  The solder lugs of the steering motors were vulnerable, got caught in the workbench rug and one broke off.  Fortunately was able to bare enough pad to re-solder!

One interim solution was some Meccano cylinders in Roberto's collection.  See photo.

A permanent solution "in keeping" with the rover was the addition of 1.5" channels with a pair channel connectors arching over each corner motor.  (same Servo City source).  See photo.

Would like to try the third option of 3D printed motor caps to match the encoder mounts.
![20181130_103247](https://user-images.githubusercontent.com/35434147/49704408-3249b880-fbd8-11e8-9658-6c9a882eb6dd.jpg)
![img_4249](https://user-images.githubusercontent.com/35434147/49704416-5e653980-fbd8-11e8-8404-455fd80f40b6.JPG)

Not sure how to make a Pull Request so offering this as an Issue.

Jim Phelan
Mars rover project lead
**Houston Robotics**

**Comment by ericjunkins** [comment]
I've added the STL and solidworks parts with commit a9d898172 , you can find these parts at 

https://github.com/nasa-jpl/open-source-rover/tree/master/Mechanical/Corner%20Steering/CAD/3D%20Printed%20Parts

These would be press fit into the channel, however we also used heat set inserts to bolt them down, which you can get at https://www.mcmaster.com/93365a130
