### ISSUE TITLE
LED Display directions out of date

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/open-source-rover#73]
LED Display directions out of date
Electrical Build, Secton 4, Connecting the LED Matrix, refers to an Adafruit tutorial:
https://learn.adafruit.com/connecting-a-16x32-rgb-led-matrix-panel-to-a-raspberry-pi/overview
which, in turn, refers to a Henner Zeller github:
https://github.com/Boomerific/rpi-rgb-led-matrix
Unfortunately, the Zeller github has changed and the Adafruit directions no longer work.
Fortunately, trying to run the obsolete Zeller code results in an error message that directs you to another Demo folder.  We're still chasing that rabbit.  If NASA/JPL or any of the teams that have crossed this particular bridge ahead of us could post a clear path to testing the LED display we would all appreciate it!

Jim Phelan
Mars rover project lead
**Houston Robotics**

**Comment by vssystemluba** [comment]
The osr-rover-code repository contains all the code necessary to run the LED matrix.  Simply clone that repository and follow the steps outlined in our Software Steps.pdf document to get the matrix running.  See section 2.2 of the Software Steps.pdf guide where we add the `-s` flag in the init script, which handles everything for running the LED matrix. 

We added a link to the adafruit tutorial to provide additional context, not intending that it be followed exactly to get the LED matrix up and running.  I have added some additional clarity in the Elecrtical Build document explaining this.  I apologize for the confusion it caused!
