### ISSUE TITLE
Conflicting drive motors in parts list and wish list

### ISSUE THREAD

**Issue by xtream1101** [nasa-jpl/open-source-rover#8]
In the parts list for the drive motors it says to get the 378:1 Gear Motor, but in the wishlist https://www.pololu.com/wishlist/1J10953 it has the 172:1 version for the drive motors.
Could which ever is incorrect be updated for consistency?

**Comment by ericjunkins** [comment]
I've updated the master parts list to be consistent with the wish list. 

We are looking into how to/where best to have a place for discussion and information about changing, upgrading, and modifying parts to fit more individual wants for project goals. Motor selection would fall under this category, where some might care more about speed, some more about torque and climbing capability etc.
