### ISSUE TITLE
Cannot access the Digikey parts list

### ISSUE THREAD

**Issue by xtream1101** [nasa-jpl/open-source-rover#9]
Cannot access the parts list for digikey https://www.digikey.com/BOM/View/Index/7594245 which is listed in the cart-share section.

**Comment by ericjunkins** [comment]
It appears that the Digikey BOM does not work the way we had initially thought for sharing the cart, so for now I've added a folder with a Bill of materials CSV file that you can upload to their BOM Manager. We will search for a possible better solution as well.
