### ISSUE TITLE
Change Connector J10

### ISSUE THREAD

**Issue by ericjunkins** [nasa-jpl/open-source-rover#93]
Standard cables don't exist in the necessary length for what is currently the J10 connector from monolithic pcb to arduino sheild.

proposed cable/connector is:
  * https://www.digikey.com/product-detail/en/jst-sales-america-inc/A06KR06KR26E51B/455-3148-ND/6194803
  * https://www.digikey.com/product-detail/en/jst-sales-america-inc/B6B-PH-K-S-LF-SN/455-1708-ND/926615

**Comment by vssystemluba** [comment]
Completed
