### ISSUE TITLE
Enhancement - mini rc version

### ISSUE THREAD

**Issue by johndpope** [nasa-jpl/open-source-rover#95]
With so many eye balls on this project - it would be cool if someone could pick this up with effort to scale down project to size of a remote control car. Would make a neat smaller scale project.

**Comment by johndpope** [comment]
![1449458364m_splash](https://user-images.githubusercontent.com/289994/53466541-7c8b5900-3aa6-11e9-940a-a30957c84b7a.jpg)
http://www.moc-pages.com/moc.php/422507

**Comment by rcywongaa** [comment]
Checkout https://github.com/Roger-random/Sawppy_Rover

**Comment by vssystemluba** [comment]
While I love the discussion, it's not really an 'issue' against this repository, so I'm going to go ahead and close it.  I highly encourage you to continue the discussion above over on our forum at https://www.tapatalk.com/groups/jpl_opensource_rover/.
